### ISSUE TITLE
I can't solve these dependency problems

### ISSUE THREAD

**Issue by AlexGithubUser** [Jiawei-Yang/FreeNeRF#14]
Oryx 0.2.1 is looking for Jaxlib 0.1.68 which doesn't exist. Its not on pypi.org. 
ERROR: Could not find a version that satisfies the requirement jaxlib==0.1.68 (from oryx) (from versions: none)
ERROR: No matching distribution found for jaxlib==0.1.68
I have tryed installing different versions of oryx but then they require different versions of Jaxlib and I have been repeatedly defeated trying to install the correct iteration of jax or jaxlib.  I'll try some more when I have more time and patience.

**Comment by Lizhen-sde** [comment]
I have the same problem, jaxlib version 0.1.68 is no longer available on PyPi, so I can't install it directly from PyPi via pip.

**Comment by guangxuwang** [comment]
same error

**Comment by Jiawei-Yang** [comment]
Sorry guys, I will try to refactorize the dependency issue next week to enable a smoother usage of this codebase. Stay tuned!

**Comment by leslieburke** [comment]
same error

**Comment by Mabel0403** [comment]
same error :(

**Comment by annci62** [comment]
conda create -n freenerf -c conda-forge python=3.6.15
conda activate freenerf
pip install --upgrade jaxlib==0.1.68+cuda110 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install -r requirements.txt

requirements.txt：
gin-config==0.5.0
absl-py==0.15.0
**six==1.15.0
decorator==4.3
torch==1.10.1
typing-extensions==3.10.0**
flax==0.3.5
tensorflow==2.6.2
opencv-python==4.5.5.62
oryx==0.2.1
jax==0.2.16
scikit-image==0.17.2
dm-pix==0.3.0
tqdm
wandb
lpips
mediapy==1.0.0
if the following two incompatibilities appear, don't worry， you still can train
![image](https://github.com/Jiawei-Yang/FreeNeRF/assets/22721741/5bf3213a-615f-4297-b6de-55991dc2c2d6)

**Comment by AlexGithubUser** [comment]
Thank you for your hard work.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Jiawei-Yang** [comment]
Hi guys, sorry for this super late reply. But I think this issue can be addressed by following this thread: https://github.com/google/jax/issues/11142#issuecomment-1158923930

**Comment by mvp18** [comment]
> conda create -n freenerf -c conda-forge python=3.6.15 conda activate freenerf pip install --upgrade jaxlib==0.1.68+cuda110 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html pip install -r requirements.txt
> 
> requirements.txt： gin-config==0.5.0 absl-py==0.15.0 **six==1.15.0 decorator==4.3 torch==1.10.1 typing-extensions==3.10.0** flax==0.3.5 tensorflow==2.6.2 opencv-python==4.5.5.62 oryx==0.2.1 jax==0.2.16 scikit-image==0.17.2 dm-pix==0.3.0 tqdm wandb lpips mediapy==1.0.0 if the following two incompatibilities appear, don't worry， you still can train ![image](https://private-user-images.githubusercontent.com/22721741/258992051-5bf3213a-615f-4297-b6de-55991dc2c2d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Njg2NzAsIm5iZiI6MTcxMjc2ODM3MCwicGF0aCI6Ii8yMjcyMTc0MS8yNTg5OTIwNTEtNWJmMzIxM2EtNjE1Zi00Mjk3LWI2ZGUtNTU5OTFkYzJjMmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE2NTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlODc4NjY5Mjg3MjZjMWVmOTBkOGJiZTkwNjhlMDIyNWJjMGE2YjVmODk1ZmI1OGQ3ZGJiYjgxNThlZGZmYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._kyttCv0LhSykEkGwIZXSxoxcyxR0vdmRctfRvZ7odQ)

Hi,

Could you please share the versions of ``dm-pix`` and ``chex`` you have installed? ``dm-pix`` is dependent on ``chex``, which for some reason, tries to reference functions in newer versions of jax. Even after many trials, I can't seem to find the right combination of versions of these packages that are compatible with the required versions of ``flax``, ``jax``, and ``jaxlib``.

**Comment by YeJiangnan1029** [comment]
> > conda create -n freenerf -c conda-forge python=3.6.15 conda activate freenerf pip install --upgrade jaxlib==0.1.68+cuda110 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html pip install -r requirements.txt
> > requirements.txt： gin-config==0.5.0 absl-py==0.15.0 **six==1.15.0 decorator==4.3 torch==1.10.1 typing-extensions==3.10.0** flax==0.3.5 tensorflow==2.6.2 opencv-python==4.5.5.62 oryx==0.2.1 jax==0.2.16 scikit-image==0.17.2 dm-pix==0.3.0 tqdm wandb lpips mediapy==1.0.0 if the following two incompatibilities appear, don't worry， you still can train ![image](https://private-user-images.githubusercontent.com/22721741/258992051-5bf3213a-615f-4297-b6de-55991dc2c2d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Njg2NzAsIm5iZiI6MTcxMjc2ODM3MCwicGF0aCI6Ii8yMjcyMTc0MS8yNTg5OTIwNTEtNWJmMzIxM2EtNjE1Zi00Mjk3LWI2ZGUtNTU5OTFkYzJjMmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE2NTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlODc4NjY5Mjg3MjZjMWVmOTBkOGJiZTkwNjhlMDIyNWJjMGE2YjVmODk1ZmI1OGQ3ZGJiYjgxNThlZGZmYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._kyttCv0LhSykEkGwIZXSxoxcyxR0vdmRctfRvZ7odQ)
> 
> Hi,
> 
> Could you please share the versions of `dm-pix` and `chex` you have installed? `dm-pix` is dependent on `chex`, which for some reason, tries to reference functions in newer versions of jax. Even after many trials, I can't seem to find the right combination of versions of these packages that are compatible with the required versions of `flax`, `jax`, and `jaxlib`.

@mvp18 Hey, bro. As python3.6 is not supported by vscode remote debugger, I've tried run the work with python 3.7 environment, and now I am running perfectly! I followed the requirements provided by @annci62 , and always got stuck with the error "AttributeError: module 'jax.random' has no attribute 'KeyArray'". The most solution to solve this problem is downgrading the jax lib from newest to lower than 0.4.23 version. However, our installed jax and jaxlib versions are 0.2.16 and 0.1.68+cuda110, which is far earlier than 0.4.23. So I geuss the attribute "KeyArray" might be added at a certain newer version. Since the error is reported by chex lib, downgrading chex verison may could prevent it from using "not supported" attribute. When I downgrade my chex lib version to 0.1.0, it works!

Here is my pip list:
Package                 Version
----------------------- ------------------
absl-py                 0.15.0
astunparse              1.6.3
backcall                0.2.0
cached-property         1.5.2
cachetools              4.2.4
certifi                 2022.12.7
charset-normalizer      3.3.2
chex                    0.1.0
clang                   5.0
click                   8.1.7
cloudpickle             2.2.1
cycler                  0.11.0
decorator               4.3.0
dm-pix                  0.3.0
dm-tree                 0.1.8
docker-pycreds          0.4.0
flatbuffers             1.12
flax                    0.3.5
fonttools               4.38.0
gast                    0.4.0
gin-config              0.5.0
gitdb                   4.0.11
GitPython               3.1.18
google-auth             1.35.0
google-auth-oauthlib    0.4.6
google-pasta            0.2.0
grpcio                  1.62.2
h5py                    3.1.0
idna                    3.7
imageio                 2.31.2
importlib-metadata      6.7.0
ipython                 7.34.0
jax                     0.2.16
jaxlib                  0.1.68+cuda110
jedi                    0.19.1
keras                   2.6.0
Keras-Preprocessing     1.1.2
kiwisolver              1.4.5
lpips                   0.1.4
Markdown                3.4.4
MarkupSafe              2.1.5
matplotlib              3.5.3
matplotlib-inline       0.1.6
mediapy                 1.0.0
msgpack                 1.0.5
networkx                2.6.3
numpy                   1.19.5
oauthlib                3.2.2
opencv-python           4.5.5.62
opt-einsum              3.3.0
optax                   0.0.9
oryx                    0.2.1
packaging               24.0
parso                   0.8.4
pexpect                 4.9.0
pickleshare             0.7.5
Pillow                  9.5.0
pip                     22.3.1
platformdirs            2.6.1
prompt_toolkit          3.0.47
protobuf                3.20.0
psutil                  6.0.0
ptyprocess              0.7.0
pyasn1                  0.5.1
pyasn1-modules          0.3.0
Pygments                2.17.2
pyparsing               3.1.2
python-dateutil         2.9.0.post0
PyWavelets              1.3.0
PyYAML                  6.0.1
requests                2.31.0
requests-oauthlib       2.0.0
rsa                     4.9
scikit-image            0.17.2
scipy                   1.7.3
sentry-sdk              2.8.0
setproctitle            1.3.3
setuptools              65.6.3
six                     1.15.0
smmap                   5.0.1
tensorboard             2.6.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
tensorflow              2.6.2
tensorflow-estimator    2.6.0
termcolor               1.1.0
tfp-nightly             0.14.0.dev20210630
tifffile                2021.11.2
toolz                   0.12.1
torch                   1.10.1
torchvision             0.11.2
tqdm                    4.66.4
traitlets               5.9.0
typing-extensions       3.7.4
urllib3                 2.0.7
wandb                   0.17.4
wcwidth                 0.2.13
Werkzeug                2.2.3
wheel                   0.38.4
wrapt                   1.12.1
zipp                    3.15.0
